import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const src = `${root}dist/index.js`;
const dest = `${root}docs/airmidi.js`;

const built = readFileSync(src, "utf8").replace(/\/\/# sourceMappingURL.*\n?$/, "");
const banner = `// Generated by \`npm run build:docs\` from dist/index.js — do not edit directly.\n`;

writeFileSync(dest, banner + built);
console.log(`Wrote ${dest}`);
